In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

In [2]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

In [3]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /home/codespace/anaconda3/lib/python3.9/site-packages (16.1.0)
Requirement already satisfied: numpy>=1.16.6 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pyarrow) (1.21.5)

#### Question 1:
Read the data for January. How many columns are there?

In [4]:
df = pd.read_parquet('./data/yellow_tripdata_2023-01.parquet')

In [5]:
len(df.columns)

19

#### Q2. Computing duration
Now let's compute the duration variable. It should contain the duration of a ride in minutes.

What's the standard deviation of the trips duration in January?

In [6]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN

In [7]:
df['duration'] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime
df.duration = df.duration.apply(lambda td: td.total_seconds() / 60)

In [8]:
df.duration.std()

42.594351241920904

#### Q3. Dropping outliers
Next, we need to check the distribution of the duration variable. There are some outliers. Let's remove them and keep only the records where the duration was between 1 and 60 minutes (inclusive).

What fraction of the records left after you dropped the outliers?

In [9]:
df1 = df[(df.duration >= 1) & (df.duration <= 60)]

In [10]:
(len(df1) / len(df)) * 100

98.1220282212598

#### Q4. One-hot encoding
Let's apply one-hot encoding to the pickup and dropoff location IDs. We'll use only these two features for our model.

Turn the dataframe into a list of dictionaries
Fit a dictionary vectorizer
Get a feature matrix from it
What's the dimensionality of this matrix (number of columns)?

In [11]:
categorical = ['PULocationID', 'DOLocationID']
df1[categorical] = df[categorical].astype(str)

train_dicts = df1[categorical].to_dict(orient='records')

/tmp/ipykernel_8665/3176223231.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[categorical] = df[categorical].astype(str)

In [12]:
train_dicts

[{'PULocationID': '161', 'DOLocationID': '141'},
 {'PULocationID': '43', 'DOLocationID': '237'},
 {'PULocationID': '48', 'DOLocationID': '238'},
 {'PULocationID': '138', 'DOLocationID': '7'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '161', 'DOLocationID': '137'},
 {'PULocationID': '239', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '200'},
 {'PULocationID': '164', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '234', 'DOLocationID': '68'},
 {'PULocationID': '79', 'DOLocationID': '264'},
 {'PULocationID': '164', 'DOLocationID': '143'},
 {'PULocationID': '138', 'DOLocationID': '33'},
 {'PULocationID': '33', 'DOLocationID': '61'},
 {'PULocationID': '79', 'DOLocationID': '186'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '113', 'DOLocationID': '255'},
 {'PULocationID': '237', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '229'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '132', 'DOLocationID': '116'},
 {'PULocationID': '163', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '161', 'DOLocationID': '87'},
 {'PULocationID': '68', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '232'},
 {'PULocationID': '43', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '229'},
 {'PULocationID': '170', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '36'},
 {'PULocationID': '163', 'DOLocationID': '186'},
 {'PULocationID': '161', 'DOLocationID': '107'},
 {'PULocationID': '233', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '144', 'DOLocationID': '140'},
 {'PULocationID': '229', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '231'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '170', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '233'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '162'},
 {'PULocationID': '229', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '224'},
 {'PULocationID': '224', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '61'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '142', 'DOLocationID': '170'},
 {'PULocationID': '107', 'DOLocationID': '145'},
 {'PULocationID': '164', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '125'},
 {'PULocationID': '142', 'DOLocationID': '24'},
 {'PULocationID': '151', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '239'},
 {'PULocationID': '68', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '114'},
 {'PULocationID': '163', 'DOLocationID': '225'},
 {'PULocationID': '137', 'DOLocationID': '236'},
 {'PULocationID': '239', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '238', 'DOLocationID': '42'},
 {'PULocationID': '107', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '158'},
 {'PULocationID': '238', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '48'},
 {'PULocationID': '141', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '261'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '232'},
 {'PULocationID': '68', 'DOLocationID': '13'},
 {'PULocationID': '13', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '50'},
 {'PULocationID': '238', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '133'},
 {'PULocationID': '132', 'DOLocationID': '188'},
 {'PULocationID': '132', 'DOLocationID': '149'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '138', 'DOLocationID': '95'},
 {'PULocationID': '132', 'DOLocationID': '218'},
 {'PULocationID': '264', 'DOLocationID': '186'},
 {'PULocationID': '264', 'DOLocationID': '114'},
 {'PULocationID': '264', 'DOLocationID': '79'},
 {'PULocationID': '264', 'DOLocationID': '239'},
 {'PULocationID': '43', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '261'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '238'},
 {'PULocationID': '161', 'DOLocationID': '228'},
 {'PULocationID': '186', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '233'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '137'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '264', 'DOLocationID': '137'},
 {'PULocationID': '137', 'DOLocationID': '212'},
 {'PULocationID': '141', 'DOLocationID': '231'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '79'},
 {'PULocationID': '229', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '144'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '166'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '137'},
 {'PULocationID': '233', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '238'},
 {'PULocationID': '233', 'DOLocationID': '229'},
 {'PULocationID': '233', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '164'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '7'},
 {'PULocationID': '158', 'DOLocationID': '229'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '75'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '234'},
 {'PULocationID': '186', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '112'},
 {'PULocationID': '249', 'DOLocationID': '239'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '75'},
 {'PULocationID': '234', 'DOLocationID': '186'},
 {'PULocationID': '246', 'DOLocationID': '13'},
 {'PULocationID': '234', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '90'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '4', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '141', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '48'},
 {'PULocationID': '229', 'DOLocationID': '236'},
 {'PULocationID': '43', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '143', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '25'},
 {'PULocationID': '132', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '239'},
 {'PULocationID': '148', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '239'},
 {'PULocationID': '107', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '249'},
 {'PULocationID': '164', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '170'},
 {'PULocationID': '162', 'DOLocationID': '170'},
 {'PULocationID': '142', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '151'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '33'},
 {'PULocationID': '186', 'DOLocationID': '97'},
 {'PULocationID': '236', 'DOLocationID': '137'},
 {'PULocationID': '107', 'DOLocationID': '162'},
 {'PULocationID': '162', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '232'},
 {'PULocationID': '148', 'DOLocationID': '170'},
 {'PULocationID': '137', 'DOLocationID': '13'},
 {'PULocationID': '170', 'DOLocationID': '113'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '79', 'DOLocationID': '161'},
 {'PULocationID': '234', 'DOLocationID': '125'},
 {'PULocationID': '211', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '45'},
 {'PULocationID': '231', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '229'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '43', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '91'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '114'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '132', 'DOLocationID': '265'},
 {'PULocationID': '90', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '48'},
 {'PULocationID': '186', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '125'},
 {'PULocationID': '125', 'DOLocationID': '97'},
 {'PULocationID': '144', 'DOLocationID': '50'},
 {'PULocationID': '211', 'DOLocationID': '88'},
 {'PULocationID': '87', 'DOLocationID': '13'},
 {'PULocationID': '13', 'DOLocationID': '48'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '142', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '249'},
 {'PULocationID': '158', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '256'},
 {'PULocationID': '50', 'DOLocationID': '68'},
 {'PULocationID': '114', 'DOLocationID': '239'},
 {'PULocationID': '43', 'DOLocationID': '24'},
 {'PULocationID': '24', 'DOLocationID': '243'},
 {'PULocationID': '137', 'DOLocationID': '141'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '41'},
 {'PULocationID': '239', 'DOLocationID': '42'},
 {'PULocationID': '41', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '48'},
 {'PULocationID': '114', 'DOLocationID': '68'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '237', 'DOLocationID': '143'},
 {'PULocationID': '239', 'DOLocationID': '107'},
 {'PULocationID': '186', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '42'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '246', 'DOLocationID': '233'},
 {'PULocationID': '249', 'DOLocationID': '48'},
 {'PULocationID': '246', 'DOLocationID': '61'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '142'},
 {'PULocationID': '161', 'DOLocationID': '229'},
 {'PULocationID': '164', 'DOLocationID': '234'},
 {'PULocationID': '113', 'DOLocationID': '238'},
 {'PULocationID': '142', 'DOLocationID': '41'},
 {'PULocationID': '151', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '114'},
 {'PULocationID': '50', 'DOLocationID': '48'},
 {'PULocationID': '137', 'DOLocationID': '162'},
 {'PULocationID': '233', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '193'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '79'},
 {'PULocationID': '90', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '148'},
 {'PULocationID': '142', 'DOLocationID': '181'},
 {'PULocationID': '25', 'DOLocationID': '257'},
 {'PULocationID': '164', 'DOLocationID': '90'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '13'},
 {'PULocationID': '170', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '94'},
 {'PULocationID': '132', 'DOLocationID': '80'},
 {'PULocationID': '107', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '107'},
 {'PULocationID': '170', 'DOLocationID': '195'},
 {'PULocationID': '132', 'DOLocationID': '238'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '237'},
 {'PULocationID': '107', 'DOLocationID': '50'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '231'},
 {'PULocationID': '50', 'DOLocationID': '261'},
 {'PULocationID': '249', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '87'},
 {'PULocationID': '132', 'DOLocationID': '10'},
 {'PULocationID': '234', 'DOLocationID': '87'},
 {'PULocationID': '211', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '255'},
 {'PULocationID': '132', 'DOLocationID': '95'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '170', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '236'},
 {'PULocationID': '144', 'DOLocationID': '42'},
 {'PULocationID': '238', 'DOLocationID': '167'},
 {'PULocationID': '238', 'DOLocationID': '167'},
 {'PULocationID': '234', 'DOLocationID': '231'},
 {'PULocationID': '144', 'DOLocationID': '263'},
 {'PULocationID': '161', 'DOLocationID': '127'},
 {'PULocationID': '74', 'DOLocationID': '248'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '249'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '162'},
 {'PULocationID': '141', 'DOLocationID': '89'},
 {'PULocationID': '43', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '138', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '151'},
 {'PULocationID': '229', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '141', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '263', 'DOLocationID': '145'},
 {'PULocationID': '234', 'DOLocationID': '164'},
 {'PULocationID': '107', 'DOLocationID': '186'},
 {'PULocationID': '238', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '107'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '233', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '233'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '140'},
 {'PULocationID': '237', 'DOLocationID': '161'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '233', 'DOLocationID': '223'},
 {'PULocationID': '143', 'DOLocationID': '166'},
 {'PULocationID': '24', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '141'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '140', 'DOLocationID': '47'},
 {'PULocationID': '163', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '249', 'DOLocationID': '233'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '141'},
 {'PULocationID': '264', 'DOLocationID': '263'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '162', 'DOLocationID': '140'},
 {'PULocationID': '164', 'DOLocationID': '229'},
 {'PULocationID': '246', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '68'},
 {'PULocationID': '246', 'DOLocationID': '4'},
 {'PULocationID': '246', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '140'},
 {'PULocationID': '263', 'DOLocationID': '162'},
 {'PULocationID': '249', 'DOLocationID': '223'},
 {'PULocationID': '146', 'DOLocationID': '145'},
 {'PULocationID': '142', 'DOLocationID': '229'},
 {'PULocationID': '140', 'DOLocationID': '40'},
 {'PULocationID': '231', 'DOLocationID': '164'},
 {'PULocationID': '50', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '164'},
 {'PULocationID': '170', 'DOLocationID': '237'},
 {'PULocationID': '142', 'DOLocationID': '107'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '50', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '263'},
 {'PULocationID': '166', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '143'},
 {'PULocationID': '234', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '113', 'DOLocationID': '202'},
 {'PULocationID': '237', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},

In [13]:
dv = DictVectorizer()
X_train = dv.fit_transform(train_dicts)

In [14]:
X_train.shape

(3009173, 515)

#### Q5. Training a model
Now let's use the feature matrix from the previous step to train a model.

Train a plain linear regression model with default parameters
Calculate the RMSE of the model on the training data
What's the RMSE on train?

In [15]:
def read_dataframe(filename):
    df = pd.read_parquet(filename)

    df["duration"] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime
    df.duration = df.duration.apply(lambda td: td.total_seconds()/60)

    df = df[(df.duration >= 1) & (df.duration <= 60)]

    categorical = ['PULocationID', 'DOLocationID']
    numerical = ['trip_distance']

    df[categorical] = df[categorical].astype(str)

    return df

In [16]:
df_train = read_dataframe('./data/yellow_tripdata_2023-01.parquet')
df_train.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333

In [17]:
df_val = read_dataframe('./data/yellow_tripdata_2023-02.parquet')
df_val.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,duration
0,1,2023-02-01 00:32:53,2023-02-01 00:34:34,2.0,0.30,1.0,N,142,163,2,4.4,3.50,0.5,0.00,0.0,1.0,9.40,2.5,0.00,1.683333
3,1,2023-02-01 00:29:33,2023-02-01 01:01:38,0.0,18.80,1.0,N,132,26,1,70.9,2.25,0.5,0.00,0.0,1.0,74.65,0.0,1.25,32.083333
4,2,2023-02-01 00:12:28,2023-02-01 00:25:46,1.0,3.22,1.0,N,161,145,1,17.0,1.00,0.5,3.30,0.0,1.0,25.30,2.5,0.00,13.300000
5,1,2023-02-01 00:52:40,2023-02-01 01:07:18,1.0,5.10,1.0,N,148,236,1,21.9,3.50,0.5,5.35,0.0,1.0,32.25,2.5,0.00,14.633333
6,1,2023-02-01 00:12:39,2023-02-01 00:40:36,1.0,8.90,1.0,N,137,244,1,41.5,3.50,0.5,3.50,0.0,1.0,50.00,2.5,0.00,27.950000

In [1]:
categorical = ['PULocationID', 'DOLocationID']#'PULocationID', 'DOLocationID']

dv = DictVectorizer()

train_dicts = df_train[categorical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

val_dicts = df_val[categorical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

NameError: name 'DictVectorizer' is not defined

In [ ]:
target = 'duration'
y_train = df_train[target].values
y_val = df_val[target].values

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_train)

mean_squared_error(y_train, y_pred, squared=False)

7.649261961655295

#### Q6. Evaluating the model
Now let's apply this model to the validation dataset (February 2023).

What's the RMSE on validation?

In [ ]:
y_pred = lr.predict(X_val)

mean_squared_error(y_val, y_pred, squared=False)

7.811819038564729